### ISSUE TITLE
Nested spoilers and layout breaking issues

### ISSUE THREAD

**Issue by phbaudin** [AlfredoRamos/phpbb-ext-simple-spoiler#1]
Nested spoilers don't work if no title is provided:
`[spoiler][spoiler]text[/spoiler][/spoiler]`

More problematic, this will allow any user to break the page layout:
`[quote][spoiler][/quote][/spoiler]`

**Comment by AlfredoRamos** [comment]
Yeah, but sadly that's a problem of the BBCode parser, for example you can't either do this:

```
[b][b]some text[/b][/b]
```

The same happens with `[color]` and many others.

I can't promise I'll get this fixed soon because I don't have a lot of free time, but I'll try to make an event in the parser or something like that.

PS: I hope that future versions of phpBB have this "feature" (nested bbcodes).

**Comment by phbaudin** [comment]
Yeah I figured that after looking for alternate solutions. The inability to nest tags is no big deal but the possibility to break the page layout is a critical issue.

I'll dig into the event system to see if this behavior can somehow be altered and I'll let you know if I find anything.

I'm also going to inquire into the future of the BBCode parser on the phpBB development forum, maybe they already plan on releasing a brand new one!

**Comment by AlfredoRamos** [comment]
The layout breaking is a issue of the bbcode parser too, you can get the same result with the default bbcodes, but if you give me more info (phpBB version, style) I'll see what I can do :sunglasses:

**Comment by phbaudin** [comment]
This is happening on 3.1.6, prosilver. :) Also, what combination of default BBCodes breaks the page layout? I haven't found any such problem with standard tags.

**Comment by AlfredoRamos** [comment]
Oh, now I see what you mean, I was still on 3.1.5 and it doesn't have that issue.

I'll look into that.

PS: Sorry for the late reply.

**Comment by AlfredoRamos** [comment]
@phbaudin I can't fix the layout breaking issue, unmatching custom bbcode tags will always break the `[quote]` bbcode.

The reason default bbcodes don't break it's because they're not parsed if the close tag don't match, custom bbcodes are always replaced with their HTML template.

Looking more deeply I can see the parser adds an extra `</div>` HTML tag, you can test it out adding a new custom bbcode.

BBCode usage: `[test]{TEXT}[/test]`
HTML replacement: `<tag>{TEXT}</tag>`

If you post:

```
[quote][test][/quote][/test]
```

It'll be replaced with:

```
<div class="content">
	<blockquote class="uncited"><div>
	<tag>
	</div></blockquote>
	</tag></div>	
</div>
```

The HTML replacement for `[quote]` is `<blockquote class="uncited"><div> **TEXT** </div></blockquote>` so you can see there's an extra `</div>` after the `</tag>` that we defined previously. It happens with any custom bbcode, even if they don't break the layout.
