### ISSUE TITLE
Extension broken after updating to phpBB 3.2.7

### ISSUE THREAD

**Issue by chrisgch** [AlfredoRamos/phpbb-ext-simple-spoiler#14]
After updating to phpBB 3.2.7, your extension is broken: The spoiler tags are no longer displayed as spoilers. How it is displayed:
![not_working_spoiler_tags](https://user-images.githubusercontent.com/4304488/58034118-1b63a680-7b26-11e9-977a-7e5eae0e6132.jpg)
How it should look like:
![how_it_should_be](https://user-images.githubusercontent.com/4304488/58034119-1bfc3d00-7b26-11e9-9a5f-dd087aafd28a.jpg)

I tried with your extension version 1.3.0 final and 1.3.1-beta (May 20, 2019).

The problem seems to be caused by vendor/s9e/text-formatter, the only phpBB part which contains the word "spoiler" in some of its files. After reverting the s9e folder to the one from phpBB 3.2.5, your extension works again normally.

**Comment by AlfredoRamos** [comment]
Well, I'm not sure what changed or where, but since phpBB 3.2.6 something broke this BBCode.

It's already fixed for phpBB >= 3.2.6 (including 3.2.7) in version 1.3.1-beta, however you need to disable it, delete its data and then enable it again.

More information:

https://www.phpbb.com/customise/db/extension/simple_spoiler_bbcode/support/topic/204016

**Comment by chrisgch** [comment]
Thanks, deleting the data helped! In my tests, I did indeed disable the plugin, delete the "cache/production" folder, and reenable the extension. I didn't think about deleting the extension data, though.

Small suggestion:
Maybe you could improve 1.3.1 before it becomes final so it detects that there is old data and deletes it by itself. This could be done by checking a "version" field, and if it's not 1.3.1 or newer, delete the data and set the field.
