### ISSUE TITLE
Spoiler mass action

### ISSUE THREAD

**Issue by sanekplus** [AlfredoRamos/phpbb-ext-simple-spoiler#38]
It seems to be a good idea to make mass spoiler opening/closing. I made a simple solution for the mass action for all spoilers on page by CTRL+click any spoiler header. It works fine with recent Chromium and almost fine with recent Firefox (CTRL also provokes current message selection, selection provokes phpbb-ext "Modern quote" to react). I'm not sure it will work fine everywhere. Maybe making a separate button for this would be better.

[spoiler.js.patch.zip](https://github.com/AlfredoRamos/phpbb-ext-simple-spoiler/files/4674983/spoiler.js.patch.zip)

**Comment by AlfredoRamos** [comment]
Hi,

There's some issues with your code:

1. I no longer use jQuery because it's not really needed for simple things like this
2. The `keydown` and `keyup` events are not really needed, the `click` event implements the `MouseEvent` interface, which gives you access the read-only `.ctrlKey` (bool) property, instead of the global variable `cntrlIsPressed` you are currently creating
3. The `this_spoiler` variable is not needed, `elements.container` already holds the same object
4. You can exit from the event when the <kbd>Ctrl</kbd> key is pressed instead of the condition `if (this_spoiler !== other_spoiler) {}` you currently have
5. Regarding the previous point, you should use `document.body.querySelectorAll()` to avoid the other code in point 3 because you are going to open all spoilers anyways

Fixing those previous issues you can get a cleaner and much more appropriate solution.

However, I don't see how that feature is useful at all, so it won't be added to this extension.
